### PR TITLE
iOSexample aria1 aria5

### PR DESCRIPTION
**Pull request by githubdam**

### CODE REVIEW

**Comment by githubdam** [comment]
Marc, please checkout the iOS_example-ARIA1_ARIA5, and if everything look okay please merge them to the remove master. <Thank you!>

**Comment by githubdam** [comment]
Marc, please review the branch iOS_example-ARIA1_ARIA5. And if everything look fine. please merge it to remove master

**Comment by githubdam** [comment]
Hi Marc, the are some unresolved conflicts that I need help merging. Thanks, Jack

**Comment by marcjohlic** [comment]
Closing due to merge conflicts - test results pulled in via a different branch

**Pull request closed without merging**
